### ISSUE TITLE
port existing offsets over?

### ISSUE THREAD

**Issue by Naville** [JosephShenton/C0F3#17]
Noticed that a few symbols are not declared nor initialized in symbols2.m

Shall we port some from existing ones like https://github.com/arx8x/v0rtex_offsets ?

**Comment by Naville** [comment]
Or are they already declared elsewhere?
I got symbol not found on f99139b  regarding:   

```
uint64_t OFFSET_BZERO;
uint64_t OFFSET_IOSURFACEROOTUSERCLIENT_VTAB;
uint64_t OFFSET_ROP_ADD_X0_X0_0x10;
uint64_t OFFSET_BCOPY;
```
Also for the record github do have a block buttom to prevent ppl from spamming your repo

**Comment by Naville** [comment]
I ported someover however the binary crashed due to some segue unidentified issue. I'm no UIKit guy so...

**Comment by iambenmitchell** [comment]
This is a know issue

**Comment by iambenmitchell** [comment]
If you want a fix follow my video. Move the arrow as I show in the video here: https://www.youtube.com/watch?v=cReZLtID5ks
