### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by tetratec** [JosephShenton/C0F3#23]
Xcode 9.2 (9C40b)
/Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/amfi.m:131:13: error: 
      'system' is unavailable: not available on iOS
            system([firstcmd UTF8String]);
            ^
In module 'Darwin' imported from /Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/libjb.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 
      'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
/Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/amfi.m:169:9: error: 
      'system' is unavailable: not available on iOS
        system("/usr/libexec/cydia/firmware.sh");
        ^
In module 'Darwin' imported from /Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/libjb.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 
      'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
/Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/amfi.m:178:13: error: 
      'system' is unavailable: not available on iOS
            system([secondcmd UTF8String]); //install
            ^
In module 'Darwin' imported from /Users/tetratec/Downloads/C0F3-master/C0F3/the_super_fun_part/libjb.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 
      'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 warning and 3 errors generated.

**Comment by JosephShenton** [comment]
hold down CMD + Click on system and jump to definition and remove __IOS_PROHIbITED
