### ISSUE TITLE
iPA or Xcode Project Not Working!

### ISSUE THREAD

**Issue by PokeAmaan** [JosephShenton/C0F3#7]
The iPA or Xcode Project isn't working for me. Plz help. For the iPA, it says there is no Info.plist

**Comment by iambenmitchell** [comment]
Read the description. Compiling isn't fully working.

**Comment by PokeAmaan** [comment]
How bout the iPA. Isn’t it already compiled?

**Comment by iambenmitchell** [comment]
Yes. but it's missing a lot of things

**Comment by JosephShenton** [comment]
Should be fixed!
