### ISSUE TITLE
Why can not support 10.2 / 10.2.1 above ip7 / 7 +? They really need help! ! ! ! ! ! 

### ISSUE THREAD

**Issue by Wang0529** [JosephShenton/C0F3#9]
10.2 / 10.2.1 on 7 / 7p have a perfect cydia experience but no one to do them would rather give up he hate him ignore him really poor people were neglected forgotten be cast aside you can solve their immediate needs Help them? They are too helpless。
10.2.1/10.2 Cydia and appsync on the 7/7 + is very complete but no one is willing to do so ignore it People seem to hate 10.2 / 10.2.1 on the ip7 / 7 + prefer to ignore them do not attach importance to timely vulnerability KPP also bypassed and did not do I do not understand。
why?
@JosephShenton

**Comment by qqlikegi** [comment]
Yes, I am iPhone7 10.2.1. very sad!

**Comment by JosephShenton** [comment]
I was going to continue soon but I can't unless /r/jailbreak chill-out and actually let me post.

**Comment by Wang0529** [comment]
Can not combine a variety of loopholes to break 10.2 / 10.2.1 rw authority above? Really hard? Keepless on 7/7p?

**Comment by Wang0529** [comment]
@JosephShenton

**Comment by Naville** [comment]
Is this even english?
For the lulz : https://github.com/iabem97/topanga/issues/75

**Comment by iambenmitchell** [comment]
German humour is no laughing matter.

**Comment by JosephShenton** [comment]
Should be fixed
